foo

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -323,7 +323,10 @@ EOF
 		if test "$have_pkgconfig" = "yes" ; then
 			CFLAGS_CURSES=$(pkg-config --cflags $libcurses 2>/dev/null)
 			LDFLAGS_CURSES=$(pkg-config --libs $libcurses 2>/dev/null)
-			if test $? -eq 0 && $CC "$tmpc" $CFLAGS $CFLAGS_CURSES \
+			echo $CC  "$tmpc" $CFLAGS $CFLAGS_CURSES 
+			$CC  "$tmpc" $CFLAGS $CFLAGS_CURSES 
+            exit
+			if test $? -eq 0 && $CC  $CFLAGS $CFLAGS_CURSES "$tmpc"\
 				$LDFLAGS $LDFLAGS_CURSES -o "$tmpo" >/dev/null 2>&1 ; then
 				CONFIG_CURSES=1
 				printf "yes\n"
@@ -351,39 +354,33 @@ fi
 
 # libtermkey is a mandatory dependency
 
-printf "checking for libtermkey... "
-cat > "$tmpc" <<EOF
-#include <termkey.h>
-
-int main(int argc, char *argv[]) {
-	TERMKEY_CHECK_VERSION;
-	return 0;
-}
-EOF
-
-if test "$have_pkgconfig" = "yes" ; then
-	CFLAGS_TERMKEY=$(pkg-config --cflags termkey 2>/dev/null)
-	LDFLAGS_TERMKEY=$(pkg-config --libs termkey 2>/dev/null)
-fi
-
-if test -z "$LDFLAGS_TERMKEY"; then
-	CFLAGS_TERMKEY=""
-	LDFLAGS_TERMKEY="-ltermkey"
-fi
-
-echo $CC  "$tmpc" $CFLAGS $CFLAGS_TERMKEY $LDFLAGS $LDFLAGS_TERMKEY $LDFLAGS_CURSES
-echo FOO
-$CC  "$tmpc" $CFLAGS $CFLAGS_TERMKEY $LDFLAGS $LDFLAGS_TERMKEY $LDFLAGS_CURSES
-echo BAR
-echo $CC  $CFLAGS "$tmpc" # $CFLAGS_TERMKEY $LDFLAGS $LDFLAGS_TERMKEY $LDFLAGS_CURSES
-$CC  $CFLAGS "$tmpc" -ltermkey # $CFLAGS_TERMKEY $LDFLAGS $LDFLAGS_TERMKEY $LDFLAGS_CURSES 
-if $CC  "$tmpc" $CFLAGS $CFLAGS_TERMKEY $LDFLAGS $LDFLAGS_TERMKEY $LDFLAGS_CURSES \
-	-o "$tmpo" >/dev/null 2>&1; then
-	printf "%s\n" "yes"
-else
-	printf "%s\n" "no"
-	fail "$0: cannot find libtermkey"
-fi
+# printf "checking for libtermkey... "
+# cat > "$tmpc" <<EOF
+# #include <termkey.h>
+# 
+# int main(int argc, char *argv[]) {
+# 	TERMKEY_CHECK_VERSION;
+# 	return 0;
+# }
+# EOF
+# 
+# if test "$have_pkgconfig" = "yes" ; then
+# 	CFLAGS_TERMKEY=$(pkg-config --cflags termkey 2>/dev/null)
+# 	LDFLAGS_TERMKEY=$(pkg-config --libs termkey 2>/dev/null)
+# fi
+# 
+# if test -z "$LDFLAGS_TERMKEY"; then
+# 	CFLAGS_TERMKEY=""
+# 	LDFLAGS_TERMKEY="-ltermkey"
+# fi
+# 
+# if $CC  "$tmpc" $CFLAGS $CFLAGS_TERMKEY $LDFLAGS $LDFLAGS_TERMKEY $LDFLAGS_CURSES \
+# 	-o "$tmpo" >/dev/null 2>&1; then
+# 	printf "%s\n" "yes"
+# else
+# 	printf "%s\n" "no"
+# 	fail "$0: cannot find libtermkey"
+# fi
 
 CONFIG_TRE=0
 REGEX_SRC=text-regex.c
